import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { CalendarDays, CheckCircle2, ChevronLeft, CircleDot, FileText, Lightbulb, Loader2, Menu, Plus, Search, Sparkles, Video, X } from "lucide-react";
import { toast } from "sonner";

const categories = [
  { value: "technology", label: "تكنولوجيا" },
  { value: "ai", label: "ذكاء اصطناعي" },
  { value: "useful_info", label: "معلومات مفيدة" },
] as const;
const statuses = [
  { value: "idea", label: "فكرة", color: "bg-amber-100 text-amber-800" },
  { value: "draft", label: "مسودة", color: "bg-blue-100 text-blue-800" },
  { value: "review", label: "قيد المراجعة", color: "bg-violet-100 text-violet-800" },
  { value: "ready", label: "جاهز للنشر", color: "bg-emerald-100 text-emerald-800" },
  { value: "published", label: "منشور", color: "bg-slate-100 text-slate-700" },
] as const;
const categoryLabel = (value: string) => categories.find(c => c.value === value)?.label ?? value;
const statusMeta = (value: string) => statuses.find(s => s.value === value) ?? statuses[0];

export default function Home() {
  const { user, loading, isAuthenticated } = useAuth();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [categoryFilter, setCategoryFilter] = useState<string>("all");
  const [dateFilter, setDateFilter] = useState<string>("all");
  const [activeVideo, setActiveVideo] = useState<any>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const utils = trpc.useUtils();
  const stats = trpc.content.stats.useQuery(undefined, { enabled: isAuthenticated });
  const youtubeStatus = trpc.youtube.status.useQuery(undefined, { enabled: isAuthenticated });
  const videos = trpc.content.list.useQuery({ search: search || undefined, status: statusFilter === "all" ? undefined : statusFilter as any, category: categoryFilter === "all" ? undefined : categoryFilter as any, dateFilter: dateFilter as any }, { enabled: isAuthenticated });
  const create = trpc.content.create.useMutation({ onSuccess: () => { utils.content.list.invalidate(); utils.content.stats.invalidate(); toast.success("اتضافت الفكرة بنجاح"); } });
  const generate = trpc.content.generate.useMutation({ onSuccess: (data) => { setForm(f => ({ ...f, ...data, status: "draft" })); toast.success("جهزتلك مسودة كاملة باللهجة المصرية"); }, onError: () => toast.error("حصلت مشكلة في التوليد، جرّب تاني") });
  const update = trpc.content.update.useMutation({ onSuccess: () => { utils.content.list.invalidate(); utils.content.stats.invalidate(); toast.success("اتحفظت التعديلات"); } });
  const advance = trpc.content.advance.useMutation({ onSuccess: () => { utils.content.list.invalidate(); utils.content.stats.invalidate(); toast.success("اتنقل المحتوى للمرحلة اللي بعدها"); } });
  const [form, setForm] = useState({ idea: "", topic: "", title: "", category: "technology", status: "idea", script: "", description: "", keywords: "" });

  const week = useMemo(() => Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - d.getDay() + i); return d; }), []);
  const scheduled = (videos.data ?? []).filter(v => v.scheduledAt);
  const submitIdea = () => { if (!form.idea.trim() || !form.topic.trim()) return toast.error("اكتب الفكرة والموضوع الأول"); create.mutate(form as any); };
  const saveVideo = () => { if (!activeVideo) return; update.mutate({ id: activeVideo.id, data: { idea: activeVideo.idea, title: activeVideo.title, category: activeVideo.category, topic: activeVideo.topic, script: activeVideo.script, description: activeVideo.description, keywords: activeVideo.keywords, scheduledAt: activeVideo.scheduledAt ? new Date(activeVideo.scheduledAt) : null, publishSlot: activeVideo.publishSlot } }); };

  if (loading) return <div className="min-h-screen grid place-items-center bg-[#f6f7f4]"><Loader2 className="animate-spin text-[#d25b3e]" /></div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#15231f] text-white grid place-items-center p-6"><div className="max-w-xl text-center"><div className="mx-auto mb-8 grid h-20 w-20 place-items-center rounded-3xl bg-[#ef6f51] shadow-2xl shadow-[#ef6f51]/20"><Sparkles size={34} /></div><p className="mb-3 text-sm font-bold tracking-[0.25em] text-[#f3aa91]">DAMAGH MASRY STUDIO</p><h1 className="text-5xl font-black leading-tight md:text-7xl">حوّل فكرتك<br /><span className="text-[#ef6f51]">لفيديو جامد.</span></h1><p className="mx-auto mt-6 max-w-md text-lg leading-8 text-white/65">استوديو بسيط وشيك يساعدك تدير أفكار قناة دماغ مصري من أول الفكرة لحد النشر.</p><Button onClick={startLogin} className="mt-9 rounded-full bg-[#ef6f51] px-8 py-6 text-base font-bold text-white hover:bg-[#d85d42]">ادخل الاستوديو <ChevronLeft className="mr-2" size={18} /></Button></div></div>;

  return <div dir="rtl" className="min-h-screen bg-[#f6f7f4] text-[#17241f]">
    <aside className={`fixed right-0 top-0 z-30 h-screen w-72 border-l border-[#dfe5df] bg-[#17241f] p-6 text-white transition-transform lg:translate-x-0 ${mobileNav ? "translate-x-0" : "translate-x-full"}`}>
      <div className="flex items-center justify-between"><div className="flex items-center gap-3"><img src="/manus-storage/damagh-masry-logo_5a5143b2.png" alt="لوجو دماغ مصري" className="h-11 w-11 rounded-2xl object-cover ring-1 ring-white/20" /><div><p className="text-xs font-bold tracking-[0.2em] text-[#f3aa91]">DAMAGH MASRY</p><h2 className="mt-1 text-2xl font-black">استوديو المحتوى</h2></div></div><button className="lg:hidden" onClick={() => setMobileNav(false)}><X /></button></div>
      <nav className="mt-14 space-y-2"><div className="nav-active"><CircleDot size={18} /> نظرة عامة</div><div className="nav-item"><Lightbulb size={18} /> الأفكار</div><div className="nav-item"><FileText size={18} /> كل المحتوى</div><div className="nav-item"><CalendarDays size={18} /> جدول النشر</div></nav>
      <div className="absolute bottom-7 right-6 left-6 space-y-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-white/50">YouTube</p>{youtubeStatus.isLoading ? <p className="mt-2 text-sm text-white/60">بنراجع حالة الربط...</p> : youtubeStatus.data == null ? <><p className="mt-1 text-sm text-white/70">القناة مش مربوطة</p><a href="/api/youtube/connect" className="mt-2 block rounded-lg bg-[#ef6f51] px-3 py-2 text-center text-sm font-bold">اربط قناتك</a></> : <p className="mt-1 truncate font-bold text-[#9fe1bf]">متصل: {youtubeStatus.data.channelTitle}</p>}</div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs text-white/50">مسجّل الدخول</p><p className="mt-1 truncate font-bold">{user?.name ?? "صانع المحتوى"}</p></div></div>
    </aside>
    {mobileNav && <div className="fixed inset-0 z-20 bg-black/30 lg:hidden" onClick={() => setMobileNav(false)} />}
    <main className="lg:mr-72">
      <header className="flex items-center justify-between border-b border-[#dfe5df] bg-[#f6f7f4]/90 px-5 py-5 backdrop-blur md:px-10"><button onClick={() => setMobileNav(true)} className="lg:hidden"><Menu /></button><div><p className="text-sm font-semibold text-[#718079]">الأربعاء، 12 أغسطس 2026</p><h1 className="mt-1 text-2xl font-black md:text-3xl">أهلاً بيك يا {user?.name?.split(" ")[0] ?? "صاحب دماغ"}.</h1></div><Dialog><DialogTrigger asChild><Button className="rounded-xl bg-[#ef6f51] font-bold text-white hover:bg-[#d85d42]"><Plus size={18} className="ml-2" /> فكرة جديدة</Button></DialogTrigger><DialogContent dir="rtl" className="max-w-xl"><DialogHeader><DialogTitle className="text-2xl font-black">فكرة فيديو جديدة</DialogTitle></DialogHeader><div className="space-y-4"><Textarea placeholder="إيه الفكرة اللي في دماغك؟" value={form.idea} onChange={e => setForm({ ...form, idea: e.target.value })} className="min-h-24" /><Input placeholder="الموضوع الرئيسي" value={form.topic} onChange={e => setForm({ ...form, topic: e.target.value })} /><Select value={form.category} onValueChange={category => setForm({ ...form, category })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{categories.map(c => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select><Button disabled={generate.isPending} onClick={() => generate.mutate({ idea: form.idea, topic: form.topic || form.idea, category: form.category as any })} variant="outline" className="w-full border-[#ef6f51] text-[#c84d36]">{generate.isPending ? <Loader2 className="ml-2 animate-spin" /> : <Sparkles size={17} className="ml-2" />} ولّدلي السكريبت والعنوان والوصف</Button><Input placeholder="العنوان (اختياري قبل التوليد)" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /><Textarea placeholder="السكريبت الكامل (هيظهر هنا بعد التوليد)" value={form.script} onChange={e => setForm({ ...form, script: e.target.value })} className="min-h-48" /><Textarea placeholder="الوصف" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /><Input placeholder="الكلمات المفتاحية" value={form.keywords} onChange={e => setForm({ ...form, keywords: e.target.value })} /><Button onClick={submitIdea} className="w-full bg-[#17241f] text-white">حفظ الفكرة</Button></div></DialogContent></Dialog></header>
      <div className="p-5 md:p-10"><section className="mb-8 overflow-hidden rounded-3xl bg-[#17241f] shadow-[0_12px_40px_rgba(23,36,31,0.16)]"><img src="/manus-storage/damagh-masry-banner_8d6dc381.png" alt="غلاف دماغ مصري: تكنولوجيا وذكاء اصطناعي بالمصري" className="h-36 w-full object-cover md:h-52" /><div className="flex flex-wrap items-center justify-between gap-3 px-5 py-4 text-white"><div><p className="text-xs font-bold tracking-[0.18em] text-[#f3aa91]">DAMAGH MASRY</p><h2 className="mt-1 text-xl font-black">تكنولوجيا وذكاء اصطناعي بالمصري</h2></div><span className="rounded-full bg-white/10 px-4 py-2 text-sm text-white/75">جاهز لصناعة المحتوى</span></div></section><section className="mb-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:"كل المحتوى",value:stats.data?.total ?? 0,icon:Video,accent:"text-[#ef6f51]"},{label:"أفكار جديدة",value:stats.data?.ideas ?? 0,icon:Lightbulb,accent:"text-[#d89b27]"},{label:"قيد المراجعة",value:stats.data?.review ?? 0,icon:CircleDot,accent:"text-[#8061c7]"},{label:"جاهز للنشر",value:stats.data?.ready ?? 0,icon:CheckCircle2,accent:"text-[#3c9b72]"}].map(item => <Card key={item.label} className="border-0 shadow-[0_8px_30px_rgba(39,55,45,0.06)]"><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm font-semibold text-[#7b8982]">{item.label}</p><p className="mt-2 text-3xl font-black">{item.value}</p></div><item.icon className={item.accent} size={26} /></CardContent></Card>)}</section>
        <div className="grid gap-8 xl:grid-cols-[1.4fr_0.8fr]"><section><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-bold text-[#ef6f51]">WORKSPACE</p><h2 className="mt-1 text-2xl font-black">آخر المحتوى</h2></div><span className="text-sm text-[#7b8982]">{videos.data?.length ?? 0} فيديو</span></div><Card className="border-0 shadow-[0_8px_30px_rgba(39,55,45,0.06)]"><CardContent className="p-4"><div className="mb-4 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute right-3 top-3 text-[#9aa59f]" size={17} /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="دوّر في الأفكار والعناوين..." className="pr-10" /></div><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="w-full md:w-40"><SelectValue placeholder="الحالة" /></SelectTrigger><SelectContent><SelectItem value="all">كل الحالات</SelectItem>{statuses.map(s => <SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select><Select value={categoryFilter} onValueChange={setCategoryFilter}><SelectTrigger className="w-full md:w-44"><SelectValue placeholder="الفئة" /></SelectTrigger><SelectContent><SelectItem value="all">كل الفئات</SelectItem>{categories.map(c => <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select><Select value={dateFilter} onValueChange={setDateFilter}><SelectTrigger className="w-full md:w-40"><SelectValue placeholder="التاريخ" /></SelectTrigger><SelectContent><SelectItem value="all">كل التواريخ</SelectItem><SelectItem value="this_week">الأسبوع ده</SelectItem><SelectItem value="scheduled">المجدول فقط</SelectItem></SelectContent></Select></div><div className="space-y-2">{(videos.data ?? []).map(video => <button key={video.id} onClick={() => setActiveVideo({ ...video })} className="flex w-full items-center gap-4 rounded-xl p-3 text-right transition hover:bg-[#f1f4ef]"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#edf0e8] text-[#6f7f73]"><Video size={19} /></div><div className="min-w-0 flex-1"><p className="truncate font-bold">{video.title || video.idea}</p><a href={`/videos/${video.id}`} onClick={e => e.stopPropagation()} className="mt-1 block text-xs font-semibold text-[#ef6f51]">فتح صفحة التفاصيل</a><p className="mt-1 text-xs text-[#8b9890]">{categoryLabel(video.category)} · {new Date(video.updatedAt).toLocaleDateString("ar-EG")}</p></div><Badge className={`${statusMeta(video.status).color} border-0`}>{statusMeta(video.status).label}</Badge></button>)}{!videos.data?.length && <div className="py-14 text-center text-[#89968f]"><Lightbulb className="mx-auto mb-3" /><p>لسه مفيش محتوى. ابدأ بفكرة جديدة.</p></div>}</div></CardContent></Card></section>
        <section><div className="mb-4"><p className="text-sm font-bold text-[#ef6f51]">THIS WEEK</p><h2 className="mt-1 text-2xl font-black">خطة الأسبوع</h2></div><Card className="border-0 bg-[#17241f] text-white shadow-[0_8px_30px_rgba(39,55,45,0.12)]"><CardHeader><CardTitle className="flex items-center justify-between text-base"><span>جدول النشر</span><CalendarDays className="text-[#f3aa91]" size={20} /></CardTitle></CardHeader><CardContent className="space-y-2">{week.map(day => { const item = scheduled.find(v => v.scheduledAt && new Date(v.scheduledAt).toDateString() === day.toDateString()); return <div key={day.toISOString()} className="flex items-center gap-3 border-b border-white/10 py-3 last:border-0"><div className="w-12 text-center"><p className="text-[10px] text-white/45">{day.toLocaleDateString("ar-EG", { weekday: "short" })}</p><p className="text-lg font-black">{day.getDate()}</p></div><div className={`h-2 w-2 rounded-full ${item ? "bg-[#ef6f51]" : "bg-white/15"}`} /> <p className="truncate text-sm text-white/65">{item ? `${item.title} · ${item.publishSlot ?? "منصة غير محددة"}` : "مفيش فيديو مجدول"}</p></div>})}</CardContent></Card></section></div>
      </div>
    </main>
    {activeVideo && <Dialog open onOpenChange={open => !open && setActiveVideo(null)}><DialogContent dir="rtl" className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle className="text-2xl font-black">تفاصيل الفيديو</DialogTitle></DialogHeader><div className="space-y-4"><Input value={activeVideo.title} onChange={e => setActiveVideo({ ...activeVideo, title: e.target.value })} placeholder="العنوان" /><Textarea value={activeVideo.idea} onChange={e => setActiveVideo({ ...activeVideo, idea: e.target.value })} placeholder="الفكرة" /><Input value={activeVideo.topic ?? ""} onChange={e => setActiveVideo({ ...activeVideo, topic: e.target.value })} placeholder="الموضوع" /><Textarea value={activeVideo.script ?? ""} onChange={e => setActiveVideo({ ...activeVideo, script: e.target.value })} placeholder="السكريبت" className="min-h-48" /><Textarea value={activeVideo.description ?? ""} onChange={e => setActiveVideo({ ...activeVideo, description: e.target.value })} placeholder="الوصف" /><Input value={activeVideo.keywords ?? ""} onChange={e => setActiveVideo({ ...activeVideo, keywords: e.target.value })} placeholder="الكلمات المفتاحية" /><div className="grid gap-3 sm:grid-cols-2"><Input type="datetime-local" value={activeVideo.scheduledAt ? new Date(activeVideo.scheduledAt).toISOString().slice(0, 16) : ""} onChange={e => setActiveVideo({ ...activeVideo, scheduledAt: e.target.value ? new Date(e.target.value) : null })} /><Input value={activeVideo.publishSlot ?? ""} onChange={e => setActiveVideo({ ...activeVideo, publishSlot: e.target.value })} placeholder="مكان النشر / المنصة" /></div><div className="flex flex-wrap gap-3"><Button onClick={saveVideo} className="bg-[#17241f] text-white">حفظ التعديلات</Button>{activeVideo.status !== "published" && <Button onClick={() => { advance.mutate({ id: activeVideo.id }); setActiveVideo(null); }} variant="outline" className="border-[#ef6f51] text-[#c84d36]">نقل للمرحلة التالية <ChevronLeft className="mr-2" size={16} /></Button>}</div></div></DialogContent></Dialog>}
  </div>;
}
